export const ICON_DEFAULT_USER = "user-nav-profile"
export const ICON_HAMBURGER = "config-hamburger-lines"
export const ICON_ARROW_LEFT = "arrow-left"
export const ICON_ARROW_RIGHT = "arrow-right"
export const ICON_ARROW_UP = "arrow-up"